#  GAListener v1.3.2
#  http://www.minecraft-index.com

#  settings section

#  onlineonly - Only delivers rewards when the player is online.  If they are offline it will wait and deliver when they next join the server!
#  luckyvote - Enables the lucky voting section, this allows voters to have a random chance to receive additional rewards when they vote.
#  permvote - Enables the permission voting section, this allows voters to receive different rewards based upon their permissions.
#  cumulative - Enables the cumulative voting section, this allows voters to receive rewards once they have reached a certain number of votes.
#  broadcastqueue - Show broadcast message for queued votes.
#  broadcastoffline - Show broadcast message for offline queued votes.
#  broadcastrecent - Show broadcast message to recent voters (last 24 hours)
#  votecommand - Enables the /vote command which will show the message contained in the votemessage section at the bottom of the config.
#  rewardcommand - Enables the /rewards command which will show a list of all the cumulative voting rewards.
#  joinmessage - Show the message contained in the joinmessage section at the bottom of this config when a player joins the server.
#  voteremind - Message players who haven't voted in the last 24 hours. Shows the message contained in the remindmessage section at the bottom of this config.
#  remindseconds - How often (in seconds) between each reminder message.
#  ratelimit - Ignore votes received within this many seconds since the last vote for the same player on the same site.  This should prevent duplicate votes.
#  logfile - Log received votes to vote.log file.
#  dbMode - Database mode. Use either mysql or sqlite.
#  dbFile - Database filename for SQLite.
#  dbHost - Database IP / Hostname for MySQL.
#  dbPort - Database port for MySQL.
#  dbUser - Database username for MySQL.
#  dbPass - Database password for MySQL.
#  dbName - Database name for MySQL.
#  dbPrefix - Database table prefix.

settings:
  onlineonly: true
  luckyvote: false
  permvote: false
  cumulative: false
  broadcastqueue: true
  broadcastrecent: true
  broadcastoffline: false
  votecommand: true
  rewardcommand: false
  joinmessage: true
  voteremind: false
  remindseconds: 300
  ratelimit: 10
  logfile: false
  dbMode: 'sqlite'
  dbFile: 'GAL.db'
  dbHost: 'localhost'
  dbPort: 3306
  dbUser: 'root'
  dbPass: ''
  dbName: 'GAL'
  dbPrefix: ''

#  services section (default is used if service doesn't exist)
#  The example below would give 5 diamonds per vote.

services:
  default:
    broadcast: '{GREEN}{username} {GOLD}has voted @ {GREEN}{service} {GOLD}and received {GREEN}5 Diamonds!'
    playermessage: '{GREEN}Thanks for voting at {AQUA}{service}!'
    commands: 
    - '/give {username} 264 5'
  MC-Index:
    broadcast: '{GREEN}{username} {GOLD}has voted @ {GREEN}MC-Index.com {GOLD}and received {GREEN}10 Diamonds!'
    playermessage: '{GREEN}Thanks for voting at {AQUA}{service}!'
    commands: 
    - '/give {username} 264 5'

#  luckyvotes section
#  The example below would give a 1 in 10 chance of a voter receiving an extra $1000, and a 1 in 50 chance of an extra $1000 and 100XP.

luckyvotes:
  '10':
    broadcast: '{GREEN}{username} {GOLD}was lucky and received an {GREEN}extra $1000!'
    playermessage: '{GREEN}You were lucky and received an extra $1000!'
    commands:
    - '/eco give {username} 1000'
  '50':
    broadcast: '{GREEN}{username} {GOLD}was super lucky and received an {GREEN}extra 100 XP and $1000!'
    playermessage: '{GREEN}You were super lucky and received an {GREEN}extra 100 XP and $1000!'
    commands:
    - '/xp give {username} 100'
    - '/eco give {username} 1000'

#  permission reward section
#  This example would give players with the permission node "gal.double" 10 Diamonds instead of their regular reward.

perms:
  double:
    broadcast: '{GREEN}{username} {GOLD}has voted @ {GREEN}{service} {GOLD}and received {GREEN}10 Diamonds!'
    playermessage: '{GREEN}Thanks for voting at {AQUA}{service}!'
    commands: 
    - '/give {username} 264 10'

#  cumulative reward section
#  This example would give players 20 Diamonds once they have reached a total of 10 votes.

cumulative:
  '10':
    broadcast: '{GREEN}{username} {GOLD}has voted a total of {YELLOW}10 times {GOLD}and received {GREEN}20 Diamonds!'
    playermessage: '{GREEN}Thanks for voting {AQUA}10 times!'
    rewardmessage: '20x Diamond'
    commands: 
    - '/give {username} 264 20'

#  blocked - a list of worlds where rewards should be disabled, they will remain queued until the player is in an allowed world.

blocked:
- world_blocked

#  Available formatting codes for messages:

#  {service} {servicename} {SERVICE} = service name
#  {username} {player} {name} = player username
#  {votes} = current vote total
#  & = Colour Symbol to enter manual colours / control codes
#  {AQUA} {BLACK} {BLUE} {DARK_AQUA} {DARK_BLUE}
#  {DARK_GRAY} {DARK_GREEN} {DARK_PURPLE} {DARK_RED} {GOLD}
#  {GRAY} {GREEN} {LIGHT_PURPLE} {RED} {WHITE} {YELLOW} {BOLD}
#  {ITALIC} {UNDERLINE} {STRIKETHROUGH} {STRIKE} 
#  {STRIKETHROUGH} {MAGIC} {RESET}

votemessage:
- '{GOLD}-----------------------------------------------------'
- 'Vote for us every day for in game rewards and extras'
- '{GOLD}-----------------------------------------------------'
- '{AQUA}You currently have {GREEN}{votes} Votes'

remindmessage:
- '{GOLD}-----------------------------------------------------'
- 'You have not voted recently, please vote to support the server'
- '{GOLD}-----------------------------------------------------'
- '{AQUA}You currently have {GREEN}{votes} Votes'

joinmessage:
- '{GOLD}-----------------------------------------------------'
- 'Vote for us every day for in game rewards and extras'
- '{GOLD}-----------------------------------------------------'
- '{AQUA}You currently have {GREEN}{votes} Votes'

#  Additional formatting codes for below:

#  {TOTAL} = vote total - used for /rewards
#  {REWARD} = current rewardmessage as specified in the cumulative reward section - used for /rewards
#  {POSITION} = current rank - used for /votetop
#  {username} = player name - used for /votetop

rewardformat: '{GREEN}{TOTAL} Votes {GRAY}- {AQUA}{REWARD}'
votetopformat: '{POSITION}. {GREEN}{username} - {WHITE}{TOTAL}'
rewardheader: 
- '{GOLD}---------------- {WHITE}[ {DARK_AQUA}Rewards{WHITE} ] {GOLD}----------------'
votetopheader: 
- '{GOLD}---------------- {WHITE}[ {DARK_AQUA}Top Voters{WHITE} ] {GOLD}----------------'
rewardfooter: 
- '{AQUA}You currently have {GREEN}{votes} Votes'
